[build]
  command = "npm install"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild" # may delete
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/server/api/:splat"
